name: uphold_sdk
description: >-
  Uphold SDK module for use in applications web, server, flutter
author: Israel Lugo <hostelixisrael@gmail.com>
homepage: https://github.com/bmkeros/uphold_sdk_dart
version: 1.0.0

dependencies:
  http: ^0.12.0
  test: ^1.5.1+1

environment:
  sdk: ">=2.0.0 <3.0.0"
